const flagMap: Record<string, string> = {
  Algeria: "🇩🇿",
  Angola: "🇦🇴",
  Argentina: "🇦🇷",
  Australia: "🇦🇺",
  Austria: "🇦🇹",
  Belgium: "🇧🇪",
  Bolivia: "🇧🇴",
  "Bosnia & Herzegovina": "🇧🇦",
  "Bosnia and Herzegovina": "🇧🇦",
  Brazil: "🇧🇷",
  Bulgaria: "🇧🇬",
  Cameroon: "🇨🇲",
  Canada: "🇨🇦",
  "Cape Verde": "🇨🇻",
  Chile: "🇨🇱",
  China: "🇨🇳",
  Colombia: "🇨🇴",
  "Costa Rica": "🇨🇷",
  Croatia: "🇭🇷",
  Cuba: "🇨🇺",
  Curaçao: "🇨🇼",
  "Czech Republic": "🇨🇿",
  Denmark: "🇩🇰",
  Ecuador: "🇪🇨",
  Egypt: "🇪🇬",
  "El Salvador": "🇸🇻",
  England: "\u{1F3F4}\u{E0067}\u{E0062}\u{E0065}\u{E006E}\u{E0067}\u{E007F}",
  France: "🇫🇷",
  Germany: "🇩🇪",
  Ghana: "🇬🇭",
  Greece: "🇬🇷",
  Haiti: "🇭🇹",
  Honduras: "🇭🇳",
  Hungary: "🇭🇺",
  Iceland: "🇮🇸",
  Iran: "🇮🇷",
  Iraq: "🇮🇶",
  Israel: "🇮🇱",
  Italy: "🇮🇹",
  "Ivory Coast": "🇨🇮",
  Jamaica: "🇯🇲",
  Japan: "🇯🇵",
  Jordan: "🇯🇴",
  Kuwait: "🇰🇼",
  Mexico: "🇲🇽",
  Morocco: "🇲🇦",
  Netherlands: "🇳🇱",
  "New Zealand": "🇳🇿",
  Nigeria: "🇳🇬",
  "North Korea": "🇰🇵",
  "Northern Ireland": "🇬🇧",
  Norway: "🇳🇴",
  Panama: "🇵🇦",
  Paraguay: "🇵🇾",
  Peru: "🇵🇪",
  Poland: "🇵🇱",
  Portugal: "🇵🇹",
  Qatar: "🇶🇦",
  "Republic of Ireland": "🇮🇪",
  Romania: "🇷🇴",
  Russia: "🇷🇺",
  "Saudi Arabia": "🇸🇦",
  Scotland: "\u{1F3F4}\u{E0067}\u{E0062}\u{E0073}\u{E0063}\u{E0074}\u{E007F}",
  Senegal: "🇸🇳",
  Serbia: "🇷🇸",
  "Serbia and Montenegro": "SCG",
  Slovakia: "🇸🇰",
  Slovenia: "🇸🇮",
  "South Africa": "🇿🇦",
  "South Korea": "🇰🇷",
  Spain: "🇪🇸",
  Sweden: "🇸🇪",
  Switzerland: "🇨🇭",
  Togo: "🇹🇬",
  "Trinidad and Tobago": "🇹🇹",
  Tunisia: "🇹🇳",
  Turkey: "🇹🇷",
  USA: "🇺🇸",
  Ukraine: "🇺🇦",
  "United Arab Emirates": "🇦🇪",
  "United States": "🇺🇸",
  Uruguay: "🇺🇾",
  Uzbekistan: "🇺🇿",
  Wales: "🏴",
  Zaire: "ZAI"
};

const fallbackCodeMap: Record<string, string> = {
  Czechoslovakia: "TCH",
  "DR Congo": "COD",
  "Dutch East Indies": "DEI",
  "East Germany": "GDR",
  "Soviet Union": "URS",
  "West Germany": "FRG",
  Yugoslavia: "YUG"
};

export function getTeamFlag(team: string) {
  return flagMap[team] ?? fallbackCodeMap[team] ?? team.slice(0, 3).toUpperCase();
}

export function isFallbackBadge(team: string) {
  const badge = getTeamFlag(team);
  return /^[A-Z0-9]{2,4}$/.test(badge);
}
